name: Build Windows Production Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Upload Release Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: localpavtv_gui_windows
          path: target/release/localpavtv_gui.exe
